export const getPokemonTypes = (pokemonName: string): string[] => {
  const typeMapping: { [key: string]: string[] } = {
    'Squirtle': ['Water'],
    'Wartortle': ['Water'], 
    'Blastoise': ['Water'],
    'Charmander': ['Fire'],
    'Charmeleon': ['Fire'],
    'Charizard': ['Fire', 'Flying'],
    'Bulbasaur': ['Grass', 'Poison'],
    'Ivysaur': ['Grass', 'Poison'],
    'Venusaur': ['Grass', 'Poison'],
    'Pikachu': ['Electric'],
    'Raichu': ['Electric'],
    'Jigglypuff': ['Normal', 'Fairy'],
    'Wigglytuff': ['Normal', 'Fairy'],
    'Psyduck': ['Water'],
    'Golduck': ['Water'],
    'Mankey': ['Fighting'],
    'Primeape': ['Fighting'],
    'Growlithe': ['Fire'],
    'Arcanine': ['Fire'],
    'Alakazam': ['Psychic'],
    'Drowzee': ['Psychic'],
    'Hypno': ['Psychic'],
    'Machamp': ['Fighting'],
    'Tentacool': ['Water', 'Poison'],
    'Tentacruel': ['Water', 'Poison'],
    'Geodude': ['Rock', 'Ground'],
    'Graveler': ['Rock', 'Ground'],
    'Golem': ['Rock', 'Ground'],
    'Magnemite': ['Electric', 'Steel'],
    'Magneton': ['Electric', 'Steel'],
    'Seel': ['Water'],
    'Dewgong': ['Water', 'Ice'],
    'Grimer': ['Poison'],
    'Muk': ['Poison'],
    'Gastly': ['Ghost', 'Poison'],
    'Haunter': ['Ghost', 'Poison'],
    'Gengar': ['Ghost', 'Poison'],
    'Voltorb': ['Electric'],
    'Electrode': ['Electric'],
    'Cubone': ['Ground'],
    'Marowak': ['Ground'],
    'Lickitung': ['Normal'],
    'Rhyhorn': ['Ground', 'Rock'],
    'Rhydon': ['Ground', 'Rock'],
    'Chansey': ['Normal'],
    'Tangela': ['Grass'],
    'Kangaskhan': ['Normal'],
    'Horsea': ['Water'],
    'Seadra': ['Water'],
    'Goldeen': ['Water'],
    'Seaking': ['Water'],
    'Staryu': ['Water'],
    'Starmie': ['Water', 'Psychic'],
    'Mr. Mime': ['Psychic', 'Fairy'],
    'Scyther': ['Bug', 'Flying'],
    'Jynx': ['Ice', 'Psychic'],
    'Electabuzz': ['Electric'],
    'Magmar': ['Fire'],
    'Pinsir': ['Bug'],
    'Tauros': ['Normal'],
    'Magikarp': ['Water'],
    'Gyarados': ['Water', 'Flying'],
    'Lapras': ['Water', 'Ice'],
    'Ditto': ['Normal'],
    'Eevee': ['Normal'],
    'Vaporeon': ['Water'],
    'Jolteon': ['Electric'],
    'Flareon': ['Fire'],
    'Omanyte': ['Rock', 'Water'],
    'Omastar': ['Rock', 'Water'],
    'Kabuto': ['Rock', 'Water'],
    'Kabutops': ['Rock', 'Water'],
    'Aerodactyl': ['Rock', 'Flying'],
    'Snorlax': ['Normal'],
    'Articuno': ['Ice', 'Flying'],
    'Zapdos': ['Electric', 'Flying'],
    'Moltres': ['Fire', 'Flying'],
    'Dratini': ['Dragon'],
    'Dragonair': ['Dragon'],
    'Dragonite': ['Dragon', 'Flying'],
    'Mewtwo': ['Psychic'],
    'Mew': ['Psychic'],
    'Spearow': ['Normal', 'Flying'],
    'Fearow': ['Normal', 'Flying'],
    'Caterpie': ['Bug'],
    'Metapod': ['Bug'],
    'Beedrill': ['Bug', 'Poison'],
    'Weedle': ['Bug', 'Poison'],
    'Kakuna': ['Bug', 'Poison'],
    'Pidgey': ['Normal', 'Flying'],
    'Pidgeotto': ['Normal', 'Flying'],
    'Pidgeot': ['Normal', 'Flying'],
    'Rattata': ['Normal'],
    'Raticate': ['Normal'],
    'Ekans': ['Poison'],
    'Arbok': ['Poison'],
    'Nidoran♂': ['Poison'],
    'Nidorino': ['Poison'],
    'Nidoking': ['Poison', 'Ground'],
    'Nidoran♀': ['Poison'],
    'Nidorina': ['Poison'],
    'Nidoqueen': ['Poison', 'Ground'],
    'Clefairy': ['Fairy'],
    'Clefable': ['Fairy'],
    'Vulpix': ['Fire'],
    'Ninetales': ['Fire'],
    'Zubat': ['Poison', 'Flying'],
    'Golbat': ['Poison', 'Flying'],
    'Oddish': ['Grass', 'Poison'],
    'Gloom': ['Grass', 'Poison'],
    'Vileplume': ['Grass', 'Poison'],
    'Paras': ['Bug', 'Grass'],
    'Parasect': ['Bug', 'Grass'],
    'Venonat': ['Bug', 'Poison'],
    'Venomoth': ['Bug', 'Poison'],
    'Diglett': ['Ground'],
    'Dugtrio': ['Ground'],
    'Meowth': ['Normal'],
    'Persian': ['Normal'],
    'Poliwag': ['Water'],
    'Poliwhirl': ['Water'],
    'Poliwrath': ['Water', 'Fighting'],
    'Abra': ['Psychic'],
    'Kadabra': ['Psychic'],
    'Bellsprout': ['Grass', 'Poison'],
    'Weepinbell': ['Grass', 'Poison'],
    'Victreebel': ['Grass', 'Poison'],
    'Slowpoke': ['Water', 'Psychic'],
    'Slowbro': ['Water', 'Psychic'],
    'Farfetch\'d': ['Normal', 'Flying'],
    'Doduo': ['Normal', 'Flying'],
    'Dodrio': ['Normal', 'Flying'],
    'Shellder': ['Water'],
    'Cloyster': ['Water', 'Ice'],
    'Onix': ['Rock', 'Ground'],
    'Krabby': ['Water'],
    'Kingler': ['Water'],
    'Exeggcute': ['Grass', 'Psychic'],
    'Exeggutor': ['Grass', 'Psychic'],
    'Hitmonlee': ['Fighting'],
    'Hitmonchan': ['Fighting'],
    'Weezing': ['Poison'],
    'Koffing': ['Poison']
  };
  
  return typeMapping[pokemonName] || ['Normal'];
};